name: wallpaper_manager
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.7

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  desktop_drop: ^0.4.1
  extended_image: ^7.0.2
  fc_native_video_thumbnail: ^0.4.0
  ffi: ^2.0.1
  file_type: 
    git: 
      url: https://github.com/guchengxi1994/file_type
  file_picker: ^5.2.6
  flutter_fancy_tree_view: ^1.0.0
  flutter_rust_bridge: 1.62.1
  flutter_smart_dialog: ^4.9.0+3
  flutter:
    sdk: flutter
  gif: ^2.2.0
  hovering: ^1.0.4
  loading_indicator: ^3.1.0
  # media_kit_libs_windows_video: ^1.0.0       # Windows package for video (& audio) native libraries. build too big
  provider: ^6.0.3
  tray_manager: ^0.2.0
  window_manager: ^0.3.1

deferred-components:
  - name: wallpaper
    libraries:
      - package:wallpaper_manager/screens/wallpaper/management_screen.dart

dev_dependencies:
  build_runner: ^2.3.3
  ffigen: ^6.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/image/no.png
    - asset/image/gallery.png
    - asset/icons/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
